#!/usr/bin/env python3
import sys
import subprocess
from time import sleep
import pifacecad

UPDATE_INTERVAL = 5 #5 seconds
GET_IP_COMMAND = "hostname --all-ip-addresses"

def run_cmd(cmd):
	return subprocess.check_output(cmd,shell=True).decode('utf-8')

def get_my_ip():
	return run_cmd(GET_IP_COMMAND)[:-1]

def wait_for_ip():
	ip = ""
	while len(ip) <=0:
		sleep(1)
		ip = get_my_ip()

def show_info():
	while True: # loop forever
		cad.lcd.clear()
		cad.lcd.write("Ben's Pi...\n")
		cad.lcd.write("IP:{}".format(get_my_ip()))
		sleep(UPDATE_INTERVAL)

def blinkit():
	i=0
	while i < 10:
		cad.lcd.backlight_off()
		sleep(1)
		cad.lcd.backlight_on()
		sleep(1)
		i = i+1

if __name__ == "__main__":
	cad = pifacecad.PiFaceCAD()
	cad.lcd.blink_off()
	cad.lcd.cursor_off()

	if "clear" in sys.argv:
		cad.lcd.clear()
		cad.lcd.display_off()
		cad.lcd.backlight_off()
	else:
		cad.lcd.backlight_on()
		cad.lcd.write("Waiting for IP...")
		wait_for_ip()
		show_info()
		blinkit()
